### ISSUE TITLE
Map Load Error Messages

### ISSUE THREAD

**Issue by drwelby** [radiantearth/stac-browser#109]
On V3 I occasionally get the error message

```
Sorry, loading the map failed.

Caused by:
Cannot set properties of undefined (setting '_leaflet_pos')
```

Stack is
```
TypeError: Cannot set properties of undefined (setting '_leaflet_pos')
    at xe (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:6:20906)
    at e._resetView (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:6:38961)
    at e.setView (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:6:27193)
    at e.fitBounds (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:6:28365)
    at a.fitBounds (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:1:27373)
    at https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:1:27085
    at u (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:7:452632)
    at Generator._invoke (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:7:452420)
    at Generator.next (https://radiantearth.github.io/stac-browser/js/chunk-5cde21ec.e8526b5d.js:7:453061)
    at n (https://radiantearth.github.io/stac-browser/js/chunk-vendors.42fcae1a.js:14:32898)
```

However, the map is rendered correctly. 

This might have something to do with back navigation and history, but I have not been able to consistently reproduce the error message yet.

**Comment by m-mohr** [comment]
Thanks for the report. Yes, something is wrong with the map, see also #95. I think I'm not doing anything wrong, but will investigate further.

**Comment by m-mohr** [comment]
Maybe related to https://github.com/Leaflet/Leaflet/issues/5774

**Comment by m-mohr** [comment]
Should be fixed.
