### ISSUE TITLE
stac-browser docker image does not build

### ISSUE THREAD

**Issue by brianloss** [radiantearth/stac-browser#338]
I attempted to pull the 3.0.1 release of stac-browser source and build the docker image. It fails with the following error. I get the same error with the 3.0.0 release which used to build fine. I'm building as per [the instructions](https://github.com/radiantearth/stac-browser#docker). 

```
#0 0.615  ERROR  Error: Cannot find module '@babel/plugin-proposal-optional-chaining'
#0 0.615         Require stack:
#0 0.615         - /app/node_modules/@babel/core/lib/config/files/plugins.js
#0 0.615         - /app/node_modules/@babel/core/lib/config/files/index.js
#0 0.615         - /app/node_modules/@babel/core/lib/index.js
#0 0.615         - /app/node_modules/@vue/cli-plugin-babel/index.js
#0 0.615         - /app/node_modules/@vue/cli-service/lib/Service.js
#0 0.615         - /app/node_modules/@vue/cli-service/bin/vue-cli-service.js
#0 0.615         - Did you mean "@babel/plugin-transform-optional-chaining"?
#0 0.615
#0 0.615         Make sure that all the Babel plugins and presets you are using
#0 0.615         are defined as dependencies or devDependencies in your package.json
#0 0.615         file. It's possible that the missing plugin is loaded by a preset
#0 0.615         you are using that forgot to add the plugin to its dependencies: you
#0 0.615         can workaround this problem by explicitly adding the missing package
#0 0.615         to your top-level package.json.
#0 0.615
#0 0.615 Error: Cannot find module '@babel/plugin-proposal-optional-chaining'
#0 0.615 Require stack:
#0 0.615 - /app/node_modules/@babel/core/lib/config/files/plugins.js
#0 0.615 - /app/node_modules/@babel/core/lib/config/files/index.js
#0 0.615 - /app/node_modules/@babel/core/lib/index.js
#0 0.615 - /app/node_modules/@vue/cli-plugin-babel/index.js
#0 0.615 - /app/node_modules/@vue/cli-service/lib/Service.js
#0 0.615 - /app/node_modules/@vue/cli-service/bin/vue-cli-service.js
#0 0.615 - Did you mean "@babel/plugin-transform-optional-chaining"?
#0 0.615
#0 0.615 Make sure that all the Babel plugins and presets you are using
#0 0.615 are defined as dependencies or devDependencies in your package.json
#0 0.615 file. It's possible that the missing plugin is loaded by a preset
#0 0.615 you are using that forgot to add the plugin to its dependencies: you
#0 0.615 can workaround this problem by explicitly adding the missing package
#0 0.615 to your top-level package.json.
#0 0.615
#0 0.615     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
#0 0.615     at resolve (node:internal/modules/cjs/helpers:116:19)
#0 0.615     at tryRequireResolve (/app/node_modules/@babel/core/lib/config/files/plugins.js:116:11)
#0 0.615     at resolveStandardizedNameForRequire (/app/node_modules/@babel/core/lib/config/files/plugins.js:150:19)
#0 0.615     at resolveStandardizedName (/app/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
#0 0.615     at loadPlugin (/app/node_modules/@babel/core/lib/config/files/plugins.js:47:20)
#0 0.615     at loadPlugin.next (<anonymous>)
#0 0.615     at createDescriptor (/app/node_modules/@babel/core/lib/config/config-descriptors.js:139:16)
#0 0.615     at createDescriptor.next (<anonymous>)
#0 0.615     at evaluateSync (/app/node_modules/gensync/index.js:251:28)

```

**Comment by m-mohr** [comment]
Something in the dependency tree removed a dependency that we need. We recently added again so that it builds again: https://github.com/radiantearth/stac-browser/commit/d29d9d51f41bba1d96c5f50d9209719657002f6b
There's no released version for it yet (you can try the main branch), but planning to release 3.0.2 soon.
