### ISSUE TITLE
Don't require Python 2 / Windows support

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-browser#36]
npm install on Windows 10 requires Python 2:

```
PS C:\projects\stac-browser> npm install

> deasync@0.1.14 install C:\projects\stac-browser\node_modules\deasync
> node ./build.js


C:\projects\stac-browser\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "C:\Users\Matthias Mohr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe"
gyp ERR! find Python - version is "3.8.5"
gyp ERR! find Python - version is 3.8.5 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python 2.7.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:303:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:132:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:221:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-python.js:267:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\stac-browser\node_modules\deasync
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
Build failed
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\netlify-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.14 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matthias Mohr\AppData\Roaming\npm-cache\_logs\2020-08-25T15_08_23_072Z-debug.log
PS C:\projects\stac-browser>
```

For me it feels like there are two things wrong with this:
1. Why is Python required for a node project?
2. Why is an outdated Python required? If it would be v3 okay, but I don't want to bloat my PC with legacy Python version tbh.

**Comment by HamedAlemo** [comment]
Interesting, I don't have Python 2 and my installation was successful (Mac). @lossyrob any thoughts?

**Comment by m-mohr** [comment]
It seems Windows is not supported by STAC Browser for dev.

I tried to nail down the issue:
1. It seems to be parcel-builder that has a dependency that requires Python 2 (on Windows). Changing the version number for parcel-bundler to `parcel-bundler/parcel#v2` makes it install.
2. Then I struggle to start STAC Browser as the npm scripts are *nix shell commands, e.g. `find dist ! -name _redirects -delete`. Removing npm run clean from the scripts, then leads to another issue.

**Comment by lossyrob** [comment]
This is unfortunate, I'm seeing issues with packages like node-gyp and deasync requiring Python for some reason.

One way around this is to make a docker-ized development environment, so that all you'd need is docker for development across platforms. Would that work for your environment @m-mohr? If so I can put in an issue for the dockerization and try to get to it before the data STAC 6 sprint.

**Comment by m-mohr** [comment]
For whatever reason, my PC crashes always when I start some kind of virtualization, including Docker. So doesn't work for me, but might work for others. I'm looking into make it run with vue-cli/webpack for a bit...

**Comment by m-mohr** [comment]
@lossyrob For your reference, I made it work with vue-cli/webpack in my fork: https://github.com/m-mohr/stac-browser/commit/99b6a1ba55e03c2eb70494b6638f68c0b462437d

That likely kills other stuff like pre-render or so, but at least I can develop now.

**Comment by m-mohr** [comment]
Migrated to vue-cli in dev.
