### ISSUE TITLE
Error not displayed for incorrect URL

### ISSUE THREAD

**Issue by drnextgis** [radiantearth/stac-browser#478]
If, instead of pointing to the root of the catalog, the stac-browser is directed to an existing URL but not the catalog one, it does not display an error. This makes it difficult to identify what went wrong, and the situation is not properly handled, as an unhandled exception is printed in the console.
```
index.js:511 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at a.q (Catalog.vue:1:126)
    at a._render (vue.runtime.esm.js:2700:28)
    at a.r (vue.runtime.esm.js:3891:27)
    at t.get (vue.runtime.esm.js:3462:33)
    at new t (vue.runtime.esm.js:3452:51)
    at Gn (vue.runtime.esm.js:3908:5)
    at a.$mount (vue.runtime.esm.js:8797:12)
    at init (vue.runtime.esm.js:4427:19)
    at m (vue.runtime.esm.js:6591:17)
    at d (vue.runtime.esm.js:6545:13)
 ```
 Example: https://radiantearth.github.io/stac-browser/#/external/catalogue.dataspace.copernicus.eu/stac/collections

**Comment by m-mohr** [comment]
Fixed in the referenced commit.
